version: "3"

networks:
  net:

  redis-replication:
    driver: bridge


services:
  url-shortener:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - net
    expose:
      - 8080
    ports:
      - '8080:8080'
    container_name: url_shortener

  redis:
    image: redis:latest
    container_name: redis_master
    ports:
      - "6379:6379"
    networks:
      - redis-replication

#  redis-slave:
#    image: redis:5.0.0
#    container_name: redis_slave
#    ports:
#      - "6380:6379"
#    command: redis-server --slaveof master 6379
#    depends_on:
#      - redis
#    networks:
#      - redis-replication