version: "3"

networks:
  net:

  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

services:
  url-shortener:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - net
    expose:
      - 8080
    ports:
      - '8080:8080'
    container_name: url_shortener

  redis:
    image: redis:latest
    container_name: redis_master
    ports:
      - "6379:6379"
    networks:
      node_net:
        ipv4_address: 172.28.1.4

#  redis-slave:
#    image: redis:5.0.0
#    container_name: redis_slave
#    ports:
#      - "6380:6379"
#    command: redis-server --slaveof master 6379
#    depends_on:
#      - redis
#    networks:
#      - redis-replication