version: "3"

networks:
  net:


services:
  url-shortener:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - net
    expose:
      - 8080
    ports:
      - '8080:8080'
    container_name: url_shortener
    depends_on:
      - redis

  redis:
    image: grokzen/redis-cluster
    container_name: url_shortner_redis
    volumes:
      - ./data/redis:/var/lib/redis
    environment:
#      - REDIS_CLUSTER_IP=0.0.0.0
      - CLUSTER_ONLY=true
#      - IP=0.0.0.0
      - NETWORK_MODE=host
    ports:
      - "7000-7004:7000-7004"
    networks:
      - net

  nginx:
    build: "./nginx"
    ports:
      - "80:80"
    depends_on:
      - "url_shortener"
    networks:
      - net

#  redis-slave:
#    image: redis:5.0.0
#    container_name: redis_slave
#    ports:
#      - "6380:6379"
#    command: redis-server --slaveof master 6379
#    depends_on:
#      - redis
#    networks:
#      - redis-replication